spring:
  application:
    name: redis-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        enabled: true
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000
  jpa:
    show-sql: true
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false

  cache:
    type: redis
    cache-names: wochat
server:
  port: 11453
