spring:
  application:
    name: redis-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        enabled: true
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000
  cache:
    type: redis
    cache-names: wochat
server:
  port: 11453
