spring:
  application:
    name: api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wochat_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update    # 自动更新
    show-sql: true        # 日志中显示sql语句
    open-in-view: false
    entityClassPackage: com.lwk.wochat.api.pojo.entity

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
