spring:
  application:
    name: api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        enabled: true
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wochat_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      ddl-auto: update    # 自动更新
    show-sql: true        # 日志中显示sql语句
    open-in-view: false
    entityClassPackage: com.lwk.wochat.api.pojo.entity
  cache:
    type: redis
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
