spring:
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wochat_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: localhost
    port: 6379
    username: ''
    password: ''
    jedis:
      pool:
        enabled: true
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 3000
  rabbitmq:
    host: localhost
    port: 5672
    username: wochat
    password: wochat
    virtual-host: /
  cache:
    type: redis
    cache-names: tokens
  jpa:
    entityClassPackage: com.lwk.wochat.api.pojo.entity

server:
  port: 11451
